// Preload de testes: envs dummy ANTES de qualquer módulo carregar (senão env.ts/oidc quebram sem IdP).
process.env.NODE_ENV ??= 'test'
process.env.AUTHENTIK_URL ??= 'https://auth.test.local'
process.env.AUTHENTIK_APP_SLUG ??= 'acdg-web'
process.env.OIDC_CLIENT_ID ??= 'acdg-web'
process.env.OIDC_CLIENT_SECRET ??= 'test-secret'
process.env.SESSION_SECRET ??= 'test-session-secret'
process.env.PUBLIC_BASE_URL ??= 'http://localhost:3000'
process.env.SOCIAL_CARE_URL ??= 'http://social-care.test.local'
process.env.PEOPLE_CONTEXT_URL ??= 'http://people-context.test.local'
process.env.ANALYSIS_BI_URL ??= 'http://analysis-bi.test.local'
